eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: sc-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: sc-eureka-ribbon
    api-b:
      path: /api-b/**
      serviceId: sc-eureka-feign