eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: sc-zuul
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data.mongodb:
    # host: 172.16.1.191
    # port: 27017
    # database: fcs
    uri: mongodb://yilijian:ylj19911013@ds161012.mlab.com:61012/leejean    
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: sc-eureka-ribbon
    api-b:
      path: /api-b/**
      serviceId: sc-eureka-feign
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"